--문자열 함수
--LOWER(), INITCAP(), UPPER()

SELECT LOWER('HELLO'), INITCAP('HELLO'), UPPER('HELLO') FROM DUAL; --DUAL은 가상테이블
SELECT LOWER(FIRST_NAME),INITCAP(FIRST_NAME), UPPER(FIRST_NAME) FROM EMPLOYEES; 
--함수는 WHERE절에도 적용된다.
SELECT FIRST_NAME FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'STEVEN'; --대문자로 비교

--LENTH() - 길이, INSTR() - 문자찾기
SELECT FIRST_NAME, LENGTH(FIRST_NAME), INSTR(FIRST_NAME, 'e') FROM EMPLOYEES;
--e가 두개 들어 있으면? 그 다음 e는?

--SUBSTR() - 문자열자르기, CONCAT() - 문자열합치기
SELECT FIRST_NAME, SUBSTR(FIRST_NAME, 1, 5) FROM EMPLOYEES; --1번째에서 5글자를 자름
SELECT FIRST_NAME, CONCAT(FIRST_NAME, LAST_NAME), --같음
                   FIRST_NAME || LAST_NAME --같음
                   FROM EMPLOYEES;

--LPAD() - 왼쪽 채우기, RPAD() - 오른쪽 채우기  
SELECT RPAD('HELLO', 10, '&') FROM DUAL;
SELECT LPAD(SALARY, 10, '#') FROM EMPLOYEES;    
SELECT RPAD(SALARY, 10, '#') FROM EMPLOYEES;

--LTRIM() - 왼쪽 제거, RTRIM() - 오른쪽 제거, TRIM() - 양쪽 제거
SELECT LTRIM('     HELLO') FROM DUAL;
SELECT LTRIM(FIRST_NAME, 'A') FROM employees; --왼쪽에 처음 발견되는 문자 'A'제거
SELECT RTRIM(FIRST_NAME, 'n') FROM EMPLOYEES;
SELECT TRIM('   HELLO   ') AS RESULT FROM DUAL;

--REPLACE() - 문자열 변경
SELECT REPLACE('TAEGU', 'T', 'D') FROM DUAL;

--중첩
SELECT REPLACE('HELLO WORLD ~!', 'HELLO', 'BYE') FROM DUAL;
SELECT REPLACE(REPLACE('HELLO WORLD ~!', 'HELLO', 'BYE'), ' ', '') FROM DUAL;

