--계정 생성
CREATE USER member IDENTIFIED BY member;
--권한부여
GRANT RESOURCE, CONNECT TO JSPPN;
--테이블스페이스 지정
ALTER USER JSPPN DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

--TABLE
CREATE TABLE MEMBER (
    M_ID VARCHAR2(30),
    M_PW VARCHAR2(30) NOT NULL, 
    M_NAME VARCHAR2(30) NOT NULL,
    M_EMAIL VARCHAR2(30),
    M_ADRESS CHAR(50),
    M_REGDATE DATE DEFAULT SYSDATE
);

SELECT * FROM MEMBER;

ALTER TABLE MEMBER ADD CONSTRAINTS MEMBER_PK PRIMARY KEY (M_ID);
