--계정 생성
CREATE USER member IDENTIFIED BY member;
--권한부여
GRANT RESOURCE, CONNECT TO JSPPN;
--테이블스페이스 지정
ALTER USER JSPPN DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;

--TABLE
--회원 테이블
CREATE TABLE MEMBER (
    M_ID VARCHAR2(30),
    M_PW VARCHAR2(30) NOT NULL, 
    M_NAME VARCHAR2(30) NOT NULL,
    M_EMAIL VARCHAR2(30),
    M_ADRESS CHAR(50)
);

--회원 PK 설정
ALTER TABLE MEMBER ADD CONSTRAINTS MEMBER_PK PRIMARY KEY (M_ID);

--테이블 생성 : 상품명
--컬럼 : 상품명, 가격, 재고, 판매자, 상품상세
CREATE TABLE PRODUCT(
    P_NAME VARCHAR2(100),
    PRICE NUMBER(10),
    STOCK NUMBER(5),
    SELLER VARCHAR2(30),
    P_DETAIL VARCHAR2(1000)
);
--상품명 PK설정
ALTER TABLE PRODUCT ADD CONSTRAINT P_NAME_PK PRIMARY KEY (P_NAME);

--리뷰 테이블 
CREATE TABLE REVIEW(
    REVIEW VARCHAR2(600) NOT NULL,
    M_ID VARCHAR2(30),
    P_NAME VARCHAR2(100)
);

select * from MEMBER;
select * from REVIEW;
select * from PRODUCT;

