CREATE TABLE HMEMBER (
	HID	VARCHAR2(20)	CONSTRAINT ID_PK PRIMARY KEY,
	HNAME	VARCHAR2(10) NOT NULL,	
	HPHONE	VARCHAR2(30) NOT NULL,	
	HADDRESS	VARCHAR2(50) NOT NULL
);

SELECT * FROM HMEMBER;
SELECT * FROM MOVIE;
