CREATE TABLE MOVIE (
    MOVIENO NUMBER(30) CONSTRAINT MOVIENO_PK PRIMARY KEY,
    MOVIENAME VARCHAR2(20) NOT NULL,
    MOVIERUN VARCHAR2(10) NOT NULL,
    MOVIEPRICE NUMBER(5) NOT NULL
);

CREATE TABLE SCHEDULE (
    SCHNO NUMBER(10) CONSTRAINT SCHEDULE_SCHNO_PK PRIMARY KEY,
    SCHTIME VARCHAR2(10) NOT NULL,
    MOVIENO NUMBER(30) CONSTRAINT SCHEDULE_MOVIENO_FK REFERENCES MOVIE(MOVIENO),
    ORDERNO NUMBER(10) CONSTRAINT SCHEDULE_ORDERNO_FK REFERENCES TICKETORDER(TORDERNO)
);

CREATE TABLE HMEMBER (
	HID	VARCHAR2(20)	CONSTRAINT ID_PK PRIMARY KEY,
	HNAME	VARCHAR2(10) NOT NULL,	
	HPHONE	VARCHAR2(30) NOT NULL,	
	HADDRESS	VARCHAR2(50) NOT NULL
);


CREATE TABLE THEATER(
           THEATER_NUM NUMBER(2)            CONSTRAINT THEATER_PK PRIMARY KEY,  --PK
            THEATER_SEAT NUMBER(2)           NOT NULL, 
           MOVIENO NUMBER(30)                 CONSTRAINT THEATER_MOVIENO_FK REFERENCES MOVIE ( MOVIENO )-- FK
);

CREATE TABLE TICKETORDER (
    TORDERNO NUMBER(10) CONSTRAINT ORDER_PK PRIMARY KEY,
    HID VARCHAR2(20) CONSTRAINT ORDER_HID_FK REFERENCES HMEMBER(HID),
    PAYNUM NUMBER(15) CONSTRAINT PAYMENT_FK REFERENCES PAYMENT(PAYNUM),
    TORDERSEAT VARCHAR2(10)
);



